package it.bailettitommaso.allena.ui.theme

import androidx.compose.ui.graphics.Color

val TealPrimaryLight = Color(0xFF2D6960)
val OnTealPrimaryLight = Color(0xFFFFFFFF)
val MintContainerLight = Color(0xFFF0F5F2)
val OnMintContainerLight = Color(0xFF2D6960)
val BackgroundLight = Color(0xFFF5F5F5)
val OnBackgroundLight = Color(0xFF1A1C1B)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1A1C1B)
val SurfaceVariantLight = Color(0xFFEAEFEC)
val OutlineLight = Color(0xFF94999A)
val SecondaryContainerLight = Color(0xFFCFE5DF)
val OnSecondaryContainerLight = Color(0xFF2D6960)
val TertiaryPurpleLight = Color(0xFF63519F)
val OnTertiaryPurpleLight = Color(0xFFFFFFFF)

val TealPrimaryDark = Color(0xFF8FCFC1)
val OnTealPrimaryDark = Color(0xFF00382F)
val MintContainerDark = Color(0xFF1E3A34)
val OnMintContainerDark = Color(0xFF8FCFC1)
val BackgroundDark = Color(0xFF121412)
val OnBackgroundDark = Color(0xFFE2E3E1)
val SurfaceDark = Color(0xFF1B1D1B)
val OnSurfaceDark = Color(0xFFE2E3E1)
val SurfaceVariantDark = Color(0xFF272B29)
val OutlineDark = Color(0xFF8C9290)
val SecondaryContainerDark = Color(0xFF2B4842)
val OnSecondaryContainerDark = Color(0xFF8FCFC1)
val TertiaryPurpleDark = Color(0xFFC5B6FF)
val OnTertiaryPurpleDark = Color(0xFF34215F)
